### PR TITLE
Adding selection and number of characters to display

### PR DESCRIPTION
**Pull request by akougblenou**
Hi I think your directive is really helpful.
However, I had some requirements in terms of how it would behave for example I wanted different display for different naming type:

```
'uttesh Ranjit' ==> UR
'Aidan Vandier Sat' ==> AV
'Gael Magma Do Borneo' ==> GM
'Adrian Di Bisumbio' ==> AB
"Antoine" ==> AN
"Antoine Kouroki" ==> AK
"Adrien Kou" ==> AK 
```

for that I built and tested the function in the following pull request
The code might not be the most efficient but it does the job, if you are okay with it I was wondering if it could be added to your directive?

### CODE REVIEW

**Comment by sudhindrapc** [comment]
Thanks @AKFourSeven for the update, 
just a small correction is needed in the code 
add this value in params object
`multiWord : attrs.multiword`

and your html will accept an extra attribute for multiword which will look like this

`<ng-letter-avatar data="C" height="70" width="70" shape="round" avatarborder="true" multiWord="true"></ng-letter-avatar>`

@uttesh great job dude.

**Comment by uttesh** [comment]
@AKFourSeven  thanks for the PR man, need to check with other changes i'm doing on this plugin, planing to add this feature in the new/existing, working on revamp of the plugin with code clean up.

**Comment by akougblenou** [comment]
@sudhindrapc @uttesh thanks for both of your feedback.
I have updated the code with multiWord missing.
Lemme know how this goes, I would be happy to have an update of this directive with this feature out of the box!

**Comment by uttesh** [comment]
@AKFourSeven updated the library with first name and last name avatar changes, setting the existing attribute 'charCount' to '2' will generate the first name and last name combined avatar. if only first name is present and charCount is 2 then it will generate for the first 2 letters.

**Comment by akougblenou** [comment]
Meaning you have accepted the pull request ?

**Comment by uttesh** [comment]
@AKFourSeven no , there was a branch conflict and i made few other changes code cleanup/format and functions. thanks

**Comment by akougblenou** [comment]
@uttesh okay I see, well glad it still did help.

**Pull request closed without merging**
